// This file is autogenerated. Changes will be overwritten.
#include "SZLP5QDJHQ/moc_calendarbackendplugin.cpp"
#include "SZLP5QDJHQ/moc_calendarview.cpp"
#include "SZLP5QDJHQ/moc_palmcalendarbackend.cpp"
