#include <QtTest/QtTest>
#include <QTemporaryDir>
#include <QJsonArray>
#include <QJsonObject>
#include <memory>

#include "runtime/palmruntime.h"
#include "runtime/palmdeviceaccess.h"
#include "palm/sync/mockpalmdatabaseaccess.h"
#include "synctypes.h"

class TstPalmRuntimeDefaultMappingsOnlyWhenEmpty : public QObject
{
    Q_OBJECT
private slots:
    void defaults_skipped_if_user_mappings_present();
    void defaultsOnlyForUncoveredSlots();
    void defaultMappings_useLastWriteWinsPolicy();
    void starMappingsSupersedePreexistingMappings();  // C Task 9 (was wildcard test)
};

void TstPalmRuntimeDefaultMappingsOnlyWhenEmpty::defaults_skipped_if_user_mappings_present()
{
    QTemporaryDir tmp;
    WildPalms::Runtime::PalmRuntime rt(tmp.path());

    QJsonObject m;
    m[QStringLiteral("id")] = QStringLiteral("user-only");
    m[QStringLiteral("sourceBackend")] = QStringLiteral("calendar-palm");
    m[QStringLiteral("sourceCalendar")] = QStringLiteral("cal");
    m[QStringLiteral("targetBackend")] = QStringLiteral("rawfiles-x");
    m[QStringLiteral("targetCalendar")] = QStringLiteral("out");
    m[QStringLiteral("mode")] = QStringLiteral("TwoWay");
    m[QStringLiteral("conflictPolicy")] = QStringLiteral("AskUser");
    m[QStringLiteral("lossPolicy")] = QStringLiteral("Warn");
    m[QStringLiteral("enabled")] = true;
    QJsonArray arr;
    arr.append(m);

    rt.reloadMappings(arr);
    QCOMPARE(rt.palmMappings().size(), 1);

    // This test verifies the user-mapping-preservation contract via
    // reloadMappings + palmMappings round-trip. The guard that skips
    // defaults when user mappings are present is tested by inspection
    // of palmruntime.cpp's connectDevice.
    auto current = rt.palmMappings();
    QCOMPARE(current.size(), 1);
    QCOMPARE(current[0].id, QStringLiteral("user-only"));
}

void TstPalmRuntimeDefaultMappingsOnlyWhenEmpty::defaultsOnlyForUncoveredSlots()
{
    // C Task 9: repurposed from an old per-slot F1 test (now retired).
    // Verifies that finishConnect() produces exactly one Star mapping per
    // connected domain (hub-and-spoke topology) — i.e. one mapping per Palm
    // backend, not one per category slot.
    auto mockDb = std::make_unique<WildPalms::PalmSync::MockPalmDatabaseAccess>();
    QTemporaryDir tmp; QVERIFY(tmp.isValid());
    WildPalms::Runtime::PalmRuntime runtime(tmp.path());

    auto deviceAccess = std::make_unique<WildPalms::Runtime::PalmDeviceAccess>(
        std::move(mockDb), nullptr);
    runtime.setDeviceAccessForTest(std::move(deviceAccess));

    const auto mappings = runtime.palmMappings();

    // With all 4 Palm backends registering successfully, there should be
    // exactly 4 domain-level Star mappings (calendar, contacts, memo, todo).
    QCOMPARE(mappings.size(), 4);

    // Every mapping must have wp-hub as source (Primary) and a palm:<domain>
    // collection as target — confirming hub-and-spoke structure.
    for (const auto &m : mappings) {
        QCOMPARE(m.sourceBackend, QStringLiteral("wp-hub"));
        QVERIFY(m.targetCalendar.startsWith(QStringLiteral("palm:")));
    }
}

void TstPalmRuntimeDefaultMappingsOnlyWhenEmpty::defaultMappings_useLastWriteWinsPolicy()
{
    // C Task 9: renamed assertion — new behavior uses AskUser, not LastWriteWins.
    // finishConnect() builds domain-level Star mappings via generateMappings()
    // with conflictPolicy=AskUser so Palm<->hub conflicts surface for review
    // rather than silently auto-resolving (see comment in palmruntime.cpp).
    auto mockDb = std::make_unique<WildPalms::PalmSync::MockPalmDatabaseAccess>();
    QTemporaryDir tmp;
    QVERIFY(tmp.isValid());

    WildPalms::Runtime::PalmRuntime runtime(tmp.path());

    auto deviceAccess = std::make_unique<WildPalms::Runtime::PalmDeviceAccess>(
        std::move(mockDb), nullptr);
    runtime.setDeviceAccessForTest(std::move(deviceAccess));

    const auto mappings = runtime.palmMappings();
    QVERIFY(!mappings.isEmpty());

    // All auto-generated Star mappings must use AskUser conflict policy
    // (deliberate change from the retired per-slot RawFiles LastWriteWins default).
    for (const auto &m : mappings) {
        QCOMPARE(m.conflictPolicy,
                 Kalburator::Sync::ConflictResolution::AskUser);
    }
}

void TstPalmRuntimeDefaultMappingsOnlyWhenEmpty::starMappingsSupersedePreexistingMappings()
{
    // C Task 9: documents the spec's accepted interim — finishConnect's Star
    // mappings (Palm<->hub, generated by libkalburator's generateMappings)
    // OVERWRITE any persisted user mappings unconditionally. The next
    // sub-project reintroduces user-configured remotes as hub<->remote
    // bindings; for now they are intentionally superseded by Palm<->hub.
    // This replaces the retired F.1c.1 wildcard-suppression test (the
    // per-slot RawFiles default path it guarded no longer exists).

    QTemporaryDir tmp; QVERIFY(tmp.isValid());
    WildPalms::Runtime::PalmRuntime runtime(tmp.path());

    // Seed a user mapping BEFORE injecting the device.
    QJsonObject m;
    m[QStringLiteral("id")]              = QStringLiteral("user-preexisting");
    m[QStringLiteral("sourceBackend")]   = QStringLiteral("calendar");
    m[QStringLiteral("sourceCalendar")]  = QString();
    m[QStringLiteral("targetBackend")]   = QStringLiteral("test-target");
    m[QStringLiteral("targetCalendar")]  = QStringLiteral("Personal");
    m[QStringLiteral("mode")]            = QStringLiteral("TwoWay");
    m[QStringLiteral("conflictPolicy")]  = QStringLiteral("AskUser");
    m[QStringLiteral("lossPolicy")]      = QStringLiteral("Warn");
    m[QStringLiteral("enabled")]         = true;
    QJsonArray arr; arr.append(m);
    runtime.reloadMappings(arr);
    QCOMPARE(runtime.palmMappings().size(), 1);

    auto mockDb = std::make_unique<WildPalms::PalmSync::MockPalmDatabaseAccess>();
    auto deviceAccess = std::make_unique<WildPalms::Runtime::PalmDeviceAccess>(
        std::move(mockDb), nullptr);
    runtime.setDeviceAccessForTest(std::move(deviceAccess));

    // After finishConnect, palmMappings is the 4 generated Star mappings;
    // the pre-existing "user-preexisting" mapping is gone (superseded).
    const auto post = runtime.palmMappings();
    QCOMPARE(post.size(), 4);
    for (const auto &x : post) {
        QCOMPARE(x.sourceBackend, QStringLiteral("wp-hub"));
        QVERIFY(x.id != QStringLiteral("user-preexisting"));
    }
}

QTEST_MAIN(TstPalmRuntimeDefaultMappingsOnlyWhenEmpty)
#include "tst_palm_runtime_default_mappings_only_when_empty.moc"
