#ifndef QPILOTSYNC_VERSION_H
#define QPILOTSYNC_VERSION_H

#define QPILOTSYNC_VERSION_MAJOR 0
#define QPILOTSYNC_VERSION_MINOR 1
#define QPILOTSYNC_VERSION_PATCH 0
#define QPILOTSYNC_VERSION_STRING "0.1.0"

#endif // QPILOTSYNC_VERSION_H
