#ifndef WILDPALMS_VERSION_H
#define WILDPALMS_VERSION_H

#define WILDPALMS_VERSION_MAJOR 0
#define WILDPALMS_VERSION_MINOR 1
#define WILDPALMS_VERSION_PATCH 0
#define WILDPALMS_VERSION_STRING "0.1.0"

#endif // WILDPALMS_VERSION_H
